### Hello everyone, in this mini notebook, we will examine some powerful numpy topics that can easily be overlooked over time.

### I hope you will remember these topics or even learn some!

# Table of Contents

1. [Array types](#1)
1. [Array creation](#2)
1. [Array manipulation](#3)
1. [Shape operations](#4)
1. [Indexing](#5)
1. [Broadcasting](#6)
1. [Matrix multiplication](#7)


In [1]:
import numpy as np

### Array types <a id=1></a>

##### We simply have four different mathematical objects in linear algebra and we can implement them in NumPy as follows:

In [2]:
scalar = np.float32(1e-1)
vector = np.array([1., 2., 3.])
matrix = np.array([[1., 2., 3. ],[4., 5., 6.]])
tensor = np.array([[[1., 2.],[3., 4.]],[[5., 6.],[7., 8.]]])

##### Their difference seems obvious, but we can see their difference in properties:

In [3]:
print(f"scalar: {scalar}; scalar_dtype: {scalar.dtype}; scalar_shape: {scalar.shape}; scalar_size: {scalar.size}; scalar_ndim: {scalar.ndim}")
print(f"vector: {vector}; vector_dtype: {vector.dtype}; vector_shape: {vector.shape}; vector_size: {vector.size}; vector_ndim: {vector.ndim}")
print(f"matrix: {matrix}; matrix_dtype: {matrix.dtype}; matrix_shape: {matrix.shape}; matrix_size: {matrix.size}; matrix_ndim: {matrix.ndim}")
print(f"tensor: {tensor}; tensor_dtype: {tensor.dtype}; tensor_shape: {tensor.shape}; tensor_size: {tensor.size}; tensor_ndim: {tensor.ndim}")

scalar: 0.10000000149011612; scalar_dtype: float32; scalar_shape: (); scalar_size: 1; scalar_ndim: 0
vector: [1. 2. 3.]; vector_dtype: float64; vector_shape: (3,); vector_size: 3; vector_ndim: 1
matrix: [[1. 2. 3.]
 [4. 5. 6.]]; matrix_dtype: float64; matrix_shape: (2, 3); matrix_size: 6; matrix_ndim: 2
tensor: [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]; tensor_dtype: float64; tensor_shape: (2, 2, 2); tensor_size: 8; tensor_ndim: 3


##### The ndim reference determines the object type. 

##### Such that, $0 \rightarrow scalar$, $1 \rightarrow vector$, $2 \rightarrow matrix$, $3+ \rightarrow tensor$

### Array creation <a id=2></a>

Detailed version [here](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [4]:
# "_like", takes another array as an input and creates one as its size.

ones_vector = np.ones(10)
zeros_tensor = np.zeros_like(tensor)
empty_matrix = np.empty_like(matrix)
fulled_matrix = np.full_like(matrix, 5)

print(ones_vector.ndim)
print(zeros_tensor.ndim)
print(empty_matrix.ndim)
print(fulled_matrix.ndim)

1
3
2
2


##### Also, we can provide range to create NumPy arrays with functions.

In [5]:
#arange creates evenly spaced array in given start and stop index [start, stop)

range_vector_1 = np.arange(0, 10, 2)
print(range_vector_1)

#linspace requires the number of points for the given interval.
range_vector_2 = np.linspace(0, 10, 5)
print(range_vector_2)

#this also works
print(np.arange(10))

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[0 1 2 3 4 5 6 7 8 9]


### Array manipulation <a id=3></a>

Detailed version [here](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [6]:
# For merging I prefer np.concatenate and np.stack

arr_1 = np.ones((2, 3))
arr_2 = np.zeros((2, 3))

arr_conc_0 = np.concatenate((arr_1, arr_2), axis=0)
print(arr_conc_0)

arr_conc_1 = np.concatenate((arr_1, arr_2), axis=1)
print(arr_conc_1)

arr_3 = np.ones((1, 3))
arr_4 = np.zeros((1, 3))

arr_stack_1 = np.stack((arr_3, arr_4), axis=-1)
print(arr_stack_1)

# hstack and vstack are also good options

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
[[[1. 0.]
  [1. 0.]
  [1. 0.]]]


In [7]:
# For splitting I prefer np.split and np.data_split. These functions are extremely similar, please check their documentation for the difference.

print(np.split(arr_conc_1, 2))
print(np.split(arr_conc_1, 2, axis= 1))

[array([[1., 1., 1., 0., 0., 0.]]), array([[1., 1., 1., 0., 0., 0.]])]
[array([[1., 1., 1.],
       [1., 1., 1.]]), array([[0., 0., 0.],
       [0., 0., 0.]])]


### Shape operations <a id=4></a>

In [8]:
arr = np.arange(8)
print(f"{arr}\t{arr.shape}")

row_vector = arr.reshape((1,8))
print(f"{row_vector}\t{row_vector.shape}")

# if you put -1, NumPy calculates the dimension for that shape.
col_vector = arr.reshape((-1, 1))
print(f"{col_vector}\t{col_vector.shape}")

matrix = arr.reshape((2,4))
print(f"{matrix}\t{matrix.shape}")

tensor = arr.reshape((2,-1,2))
print(f"{tensor}\t{tensor.shape}")

[0 1 2 3 4 5 6 7]	(8,)
[[0 1 2 3 4 5 6 7]]	(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]	(8, 1)
[[0 1 2 3]
 [4 5 6 7]]	(2, 4)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]	(2, 2, 2)


##### NumPy arrays stored as contiguous blocks in memory. Reshaping does not change the location of the array in memory. The default order is by row, one can change this by using "F" order (Fortran).

In [9]:
# Transpose operation is also important

print(f"{row_vector}, {np.transpose(col_vector)}")

print(np.allclose(row_vector, np.transpose(col_vector)))

[[0 1 2 3 4 5 6 7]], [[0 1 2 3 4 5 6 7]]
True


In [10]:
# But it is tricky for tensors. You should be careful.

tensor = np.arange(3*4*5).reshape(3,4,5)
print(tensor.shape)

tensor_transpose_default = np.transpose(tensor)
print(tensor_transpose_default.shape)

tensor_transpose_input = np.transpose(tensor, (1, 0, 2))
print(tensor_transpose_input.shape)

# you should give the order of the transpose.

(3, 4, 5)
(5, 4, 3)
(4, 3, 5)


### Indexing  <a id=5></a>

##### NumPy uses Python indexing and slicing. We can also use NumPy indexing and slicing for tensors as well.

In [11]:
arr = np.arange(10).reshape(2,5)
print(f"{arr}, {arr[::2]}")

[[0 1 2 3 4]
 [5 6 7 8 9]], [[0 1 2 3 4]]


In [12]:
arr = np.arange(24).reshape(2,3,4)
print(f"{arr}\n\n {arr[::, 0, 1]}")

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 [ 1 13]


### Broadcasting  <a id=6></a>

##### One of the most fundamental and most useful feature of the NumPy. It simply it reshapes the arrays automatically so that the inputs will be compatible. Please check quick official [tutorial](https://numpy.org/doc/stable/user/basics.broadcasting.html). 

In [13]:
a = np.array([1, 2, 3])
b = np.array([3, 3, 3])

a * b

array([3, 6, 9])

In [14]:
a = np.array([1, 2, 3])
b = 3

a * b # Possible thanks to broadcasting

array([3, 6, 9])

In [15]:
a = np.array([  [0, 0, 0],
                [1, 1, 1],
                [2, 2, 2],
                [3, 3, 3]])

b = np.array([2,2,2])

a + b

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [16]:
# One should also need to be careful. Broadcasting may lead unwanted results.

a = np.zeros((4,1))
b = np.ones((4))

a + b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Matrix Multiplication  <a id=7></a>

##### operand "@"

In [17]:
I_2 = np.eye(2)

A = np.random.randn(2,3)

print(I_2)
print(A)

print(I_2 @ A)

[[1. 0.]
 [0. 1.]]
[[ 1.48889636 -2.84198179 -0.2326285 ]
 [ 0.51688541 -1.03007908 -0.04972801]]
[[ 1.48889636 -2.84198179 -0.2326285 ]
 [ 0.51688541 -1.03007908 -0.04972801]]


### Conclusion

#### Links: [GitHub](https://github.com/ahmetTuzen/Deep_Learning_Tutorials) and [LinkedIn](https://www.linkedin.com/in/ahmet-tuzen/)